# Generated by Django 3.1.7 on 2021-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
