# Generated by Django 3.1.7 on 2021-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20210508_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
